// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/assets/file': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/assets/file.post').default>>>>
    }
    '/api/assets/files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/assets/files.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/assets/files.post').default>>>>
    }
    '/api/assets/thumbnail': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/assets/thumbnail.post').default>>>>
    }
    '/api/auth/currentUser': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/currentUser.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/currentUser.patch').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/logout').default>>>>
    }
    '/api/auth/refresh': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/refresh').default>>>>
    }
    '/api/auth/reset': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/reset.post').default>>>>
    }
    '/api/auth/sso': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/sso.post').default>>>>
    }
    '/api/auth/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/auth/test').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_magicast@0.3.5_rollup@4._d2gqw66tfjawfxwx4hwxxlk7re/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.8.1_ioredis@5.4.1_magicast@0.3.5_rollup@4.27.2/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}