// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21.11.2024, 16:01:52
const configMerger = require("/home/haex/Projekte/haexcloud/haexspace/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.27.2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/haex/Projekte/haexcloud/haexspace/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/haex/Projekte/haexcloud/haexspace/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/haex/Projekte/haexcloud/haexspace/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/haex/Projekte/haexcloud/haexspace/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/haex/Projekte/haexcloud/haexspace/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/haex/Projekte/haexcloud/haexspace/src/plugins/**/*.{js,ts,mjs}","/home/haex/Projekte/haexcloud/haexspace/src/composables/**/**/*.{js,ts,mjs}","/home/haex/Projekte/haexcloud/haexspace/src/stores/**/**/*.{js,ts,mjs}","/home/haex/Projekte/haexcloud/haexspace/src/components/**/**/*.{js,ts,mjs}","/home/haex/Projekte/haexcloud/haexspace/src/pages/**/**/*.{js,ts,mjs}","/home/haex/Projekte/haexcloud/haexspace/src/composables/**/*.{js,ts,mjs}","/home/haex/Projekte/haexcloud/haexspace/src/utils/**/*.{js,ts,mjs}","/home/haex/Projekte/haexcloud/haexspace/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/haex/Projekte/haexcloud/haexspace/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/haex/Projekte/haexcloud/haexspace/src/app.config.{js,ts,mjs}"] } }));

module.exports = config
